### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_import#1]
@jenlampton I searched first via the Project Installer and didn't find this module so spent a bunch of time porting it and then stumbled on your comment in the D7 issue queue about porting it. Doh, my bad I know!

Just tested and it's working great -- ready for an initial release to make it available to the Project Installer?

**Comment by laryn** [comment]
Before a release, I did submit a PR to fix an issue I ran across: https://github.com/backdrop-contrib/webform_import/issues/2

**Comment by jenlampton** [comment]
Tagged the first release :)
https://github.com/backdrop-contrib/webform_import/releases/tag/1.x-1.3.0
