### ISSUE TITLE
Clean up inline code comments

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform_import#9]
There are a handful of issues with inline code comments that do not meet coding standards in the following ways:
* Do not start with a capital letter
* Do not end with a period

It would also be great if the comments could be reformatted into a complete sentence in each case. If the comment is describing WHAT appears in the following lines rather than WHY, it's probably also safe to remove the comment entirely :)

This issue is a follow up to #4, where the fix to that problem introduces several of these issues.

**Comment by leeksoup** [comment]
@jenlampton - sorry about this. Nvm, re do you want me to fix -- saw your series of posts on #4 and will fix these comment issues. 

Thanks for merging the PR!

**Comment by jenlampton** [comment]
Thanks @leeksoup the important thing is that the bugs are fixed, thank you so much for working on that!
